name: 'Project Build'
description: 'Builds RocketModFix projects'
inputs:
  project_path:
    description: 'Path to project folder'
    required: true
  runtime_version:
    description: 'Build runtime version default linux-x64'
    required: false
    default: 'linux-x64'
  nuget_push:
    description: 'Push to Nuget on release?'
    required: false
    default: false
  nuget_key:
    description: 'NuGet deploy key'
    required: false
  github_token:
    description: 'GitHub token'
    required: false
outputs:
  version:
    description: "Generated version (SemVersion compatible)"
    value: ${{ steps.get-version.outputs.version }}
  is_prerelease:
    description: 'Gets if the version is a prerelease'
    value: ${{ steps.check-prerelease.outputs.is_prerelease }}
runs:
  using: "composite"
  steps:
    # Install .NET Framework reference assemblies for .NET Framework 4.8
    - name: Install .NET Framework Reference Assemblies
      run: |
        # Download and install .NET Framework 4.8 reference assemblies from official source
        mkdir -p /tmp/net48-refs
        curl -L -o /tmp/net48.zip "https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies/1.0.3/microsoft.netframework.referenceassemblies.1.0.3.nupkg"
        unzip -q /tmp/net48.zip -d /tmp/net48-refs/
        
        # Create the target directory
        mkdir -p /usr/share/dotnet/reference-assemblies/microsoft/framework/.netframework/v4.8
        
        # Copy reference assemblies to the expected location
        if [ -d "/tmp/net48-refs/build/.NETFramework/v4.8" ]; then
          cp -r /tmp/net48-refs/build/.NETFramework/v4.8/* /usr/share/dotnet/reference-assemblies/microsoft/framework/.netframework/v4.8/
        elif [ -d "/tmp/net48-refs/ref/net48" ]; then
          cp -r /tmp/net48-refs/ref/net48/* /usr/share/dotnet/reference-assemblies/microsoft/framework/.netframework/v4.8/
        fi
        
        # Clean up
        rm -rf /tmp/net48-refs /tmp/net48.zip
      shell: bash

    # Generate semver compatible version from current tag and commit hash
    - name: Create version
      id: get-version
      run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)+$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Prerelease
      id: check-prerelease
      run: "if ${{ contains(steps.get-version.outputs.version, '-') }}; then
              echo is_prerelease=true >> $GITHUB_OUTPUT;
            else
              echo is_prerelease=false >> $GITHUB_OUTPUT;
            fi"
      shell: bash

    # Commands that are used multiple times.
    # Placed in one place to make sure that the arguments would always be the same
    - name: Common commands
      id: common-commands
      run: |
        echo "dotnet-restore=dotnet restore \$PROJECT_PATH --runtime ${{ inputs.runtime_version }}" >> $GITHUB_OUTPUT
        echo "dotnet-build=dotnet build \$PROJECT_PATH --configuration Release --no-restore -p:RocketModFixVersion=${{ steps.get-version.outputs.version }} --runtime ${{ inputs.runtime_version }}" >> $GITHUB_OUTPUT
        echo "dotnet-test=dotnet test \$PROJECT_PATH --configuration Release --no-restore --no-build --runtime ${{ inputs.runtime_version }}" >> $GITHUB_OUTPUT
      shell: bash

    # Install dependencies (this needs to be a separate step from build for caching)
    - name: Install dependencies
      run: |
        ${{ steps.common-commands.outputs.dotnet-restore }}
        pwsh -File .github/actions/project-build/run-command-for-every-tests-project.ps1 "$PROJECT_PATH" '${{ steps.common-commands.outputs.dotnet-restore }}'
      env:
        PROJECT_PATH: ${{ inputs.project_path }} # Used by commands in `common-commands` step
      shell: bash

    # Build project
    - name: Build
      run: |
        ${{ steps.common-commands.outputs.dotnet-build }}
        pwsh -File .github/actions/project-build/run-command-for-every-tests-project.ps1 "$PROJECT_PATH" '${{ steps.common-commands.outputs.dotnet-build }}'
      env:
        PROJECT_PATH: ${{ inputs.project_path }} # Used by commands in `common-commands` step
      shell: bash



    # Test project
    - name: Test
      run: |
        pwsh -File .github/actions/project-build/run-command-for-every-tests-project.ps1 "$PROJECT_PATH" '${{ steps.common-commands.outputs.dotnet-test }}'
      env:
        PROJECT_PATH: ${{ inputs.project_path }} # Used by commands in `common-commands` step
      shell: bash

    # Push to GitHub packages on each commit and release
    - name: Push to NuGet (Nightly)
      if: |
        inputs.nuget_push == 'true' && (github.event_name == 'push' || 
        github.event_name == 'create' && github.event.ref_type == 'tag')
      run: dotnet nuget push ${{ inputs.project_path }}/bin/Release/*.nupkg --api-key ${{ inputs.github_token }} --source https://nuget.pkg.github.com/RocketModFix/index.json;
      shell: bash

    # Push to NuGet on each tag, but only if the tag is not a pre-release version
    - name: Push to NuGet (Release)
      if: |
        inputs.nuget_push == 'true' && steps.check-prerelease.outputs.is_prerelease == 'false' &&  
        github.event_name == 'create' && github.event.ref_type == 'tag'
      run: dotnet nuget push ${{ inputs.project_path }}/bin/Release/*.nupkg --api-key ${{ inputs.nuget_key }} --source https://api.nuget.org/v3/index.json;
      shell: bash