name: Rocket.Unturned

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.Unturned.yaml'
      - 'Rocket.Unturned/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.Unturned.yaml'
      - 'Rocket.Unturned/**'

jobs:
  Compatibility-Check:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        name: Setup .NET
        with:
          dotnet-version: 8.x

      - name: Check compatibility with original repository
        uses: ./.github/actions/compatibility-check
        with:
          fail-on-breaking-changes: true

  build:
    name: "Rocket.Unturned Build"
    runs-on: ubuntu-latest
    needs: Compatibility-Check

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x
        
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: Rocket.Unturned
        github_token: ${{ secrets.PAT }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true